### ISSUE TITLE
rss/atom feed

### ISSUE THREAD

**Issue by szabgab** [godot-rust/godot-rust.github.io#5]
I was looking for an rss/atom feed for https://godot-rust.github.io/dev/  but could not find one. Is there one?

**Comment by Bromeon** [comment]
No, there's none. I announce new blogposts on Mastodon though:
https://mastodon.gamedev.place/@GodotRust

**Comment by szabgab** [comment]
Thanks. :disappointed: If there was, I'd be happy to include it in the RSS/Atom collector for Rust I am experimenting with at https://rust-news.code-maven.com/

**Comment by Bromeon** [comment]
I don't plan on adding it, but if someone contributes a reasonably simple implementation, why not 🙂

**Comment by Bromeon** [comment]
Implemented in #7, thanks a lot to TitanNano! :+1:
